name: Build APK

on:
  workflow_dispatch:
    inputs:
      repo_to_build:
        description: 'Owner/repo to build'
        required: true
      branch:
        description: 'Branch to build'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo_to_build }}
          ref: ${{ github.event.inputs.branch }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x gradlew || true

      - name: Build release APK
        run: ./gradlew clean assembleRelease --no-daemon --stacktrace

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: built-apks
          path: '**/*.apk'